spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5431/postgres"
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: request.exchange
    queue: request.queue
    routingkey: request.routingkey
  cache:
    type: redis
    host: localhost
    port: 6379
    minutes-ttl: 60
job:
  rates-collector:
    api-name: "http://data.fixer.io/api"
    path: "/latest"
    api-key:
      name: "access_key"
      value: "a97be74337ac284ff06d8f5ab412d97f"
    fixed-rate: "3600000" # one hour
